/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

/**
 *
 * @author softliampisan
 */
public class homePage extends javax.swing.JFrame  {

    /**
     * Creates new form homePage
     */
    
//
    
    public homePage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        flexBtn = new javax.swing.JButton();
        AddingStuClassBtn = new javax.swing.JButton();
        scheduleBtn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        homeBackgrnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setLayout(null);

        flexBtn.setFont(new java.awt.Font("Nanum Myeongjo", 1, 13)); // NOI18N
        flexBtn.setText("Flex block database");
        flexBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flexBtnActionPerformed(evt);
            }
        });
        jPanel1.add(flexBtn);
        flexBtn.setBounds(240, 330, 180, 40);

        AddingStuClassBtn.setFont(new java.awt.Font("Nanum Myeongjo", 1, 13)); // NOI18N
        AddingStuClassBtn.setText("Adding Students and Courses");
        AddingStuClassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddingStuClassBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AddingStuClassBtn);
        AddingStuClassBtn.setBounds(220, 230, 220, 40);

        scheduleBtn.setFont(new java.awt.Font("Nanum Myeongjo", 1, 13)); // NOI18N
        scheduleBtn.setText("Schedule Flex block");
        scheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleBtnActionPerformed(evt);
            }
        });
        jPanel1.add(scheduleBtn);
        scheduleBtn.setBounds(240, 280, 180, 40);

        title.setFont(new java.awt.Font("Palatino", 1, 36)); // NOI18N
        title.setText("Flex Block Scheduling");
        jPanel1.add(title);
        title.setBounds(150, 130, 370, 80);

        homeBackgrnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Classes/skyback.jpg"))); // NOI18N
        jPanel1.add(homeBackgrnd);
        homeBackgrnd.setBounds(0, 0, 680, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddingStuClassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddingStuClassBtnActionPerformed
        new CourseScheduling().setVisible(true);
        
    }//GEN-LAST:event_AddingStuClassBtnActionPerformed

    private void scheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleBtnActionPerformed
        new ScheduleStudents().setVisible(true);
    }//GEN-LAST:event_scheduleBtnActionPerformed

    private void flexBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flexBtnActionPerformed
        new flexSubmissions().setVisible(true);
    }//GEN-LAST:event_flexBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new homePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddingStuClassBtn;
    private javax.swing.JButton flexBtn;
    private javax.swing.JLabel homeBackgrnd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton scheduleBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
